version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasir-lite-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - kasir-lite-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: kasir-lite-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kasir-lite-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kasir-lite-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kasir_lite
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: kasir_user
      MYSQL_PASSWORD: kasir_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kasir-lite-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kasir-lite-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: kasir_user
      PMA_PASSWORD: kasir_password
    networks:
      - kasir-lite-network
    depends_on:
      - db

networks:
  kasir-lite-network:
    driver: bridge

volumes:
  db_data:
    driver: local